version: 2

jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    steps:
      - checkout
      - run:
          name: Test
          command: dotnet test Pipeline.Web.Tests/Pipeline.Web.Tests.csproj --logger xunit
          store_test_results:
            -path: Pipeline.Web.Tests/TestResults
      - run:
          name: Publish
          command: dotnet publish Pipeline.Web/Pipeline.Web.csproj
