version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    steps:
      - checkout
      - run:
          name: Test
          command: dotnet test
      - run:
          name: Print the Current Time
          command: date
